-- ALGUMAS EXEMPLOS DE QUERYS REALIZADAS NO BANCO DE DADOS DA FECAP --

/* TABELAS UTILIZADAS*/

-- PPESSOA
-- PFUNC
-- PFFINANC
-- PEVENTO
-- PFUNCAO
-- PSINDIC
-- PSECAO
-- AHORARIO
-- PFHSTHOR

-- Query retorna o cargo de todos os colaboradores que não estão desligados e agrupa por sexo e quantidade de cargos.
-- Tabelas: PPESSOA, PFUNC e PFUNC.

SELECT 
    PFUNCAO.NOME,
    PPESSOA.SEXO,
    COUNT(PFUNCAO.NOME) AS TOTAL
FROM
PPESSOA
INNER JOIN PFUNC
ON PPESSOA.CODIGO = PFUNC.CODPESSOA
INNER JOIN PFUNCAO
ON PFUNC.CODFUNCAO = PFUNCAO.CODIGO
WHERE PFUNC.CODSITUACAO != 'D' AND PFUNC.CODRECEBIMENTO != 'H'
GROUP BY PFUNCAO.NOME, PPESSOA.SEXO
ORDER BY PFUNCAO.NOME DESC;

-- Query retorna o tempo de casa de cada colaborador e traz uma coluna com o pagamento do adicional por tempodecasa.

SELECT 
    PFUNC.CHAPA,
    PPESSOA.NOME,
    PFUNC.DATAADMISSAO,
    PFUNC.CODSITUACAO,
    PFUNC.CODRECEBIMENTO,
    PFUNC.SALARIO,
    TRUNC((MONTHS_BETWEEN(SYSDATE,PFUNC.DATAADMISSAO))/12) AS TEMPODECASA,
    CASE
        WHEN TRUNC((MONTHS_BETWEEN(SYSDATE,PFUNC.DATAADMISSAO))/12) BETWEEN 1 AND 10 THEN 5
        WHEN TRUNC((MONTHS_BETWEEN(SYSDATE,PFUNC.DATAADMISSAO))/12) BETWEEN 10 AND 20 THEN 10
        WHEN TRUNC((MONTHS_BETWEEN(SYSDATE,PFUNC.DATAADMISSAO))/12) BETWEEN 20 AND 30 THEN 13
        WHEN TRUNC((MONTHS_BETWEEN(SYSDATE,PFUNC.DATAADMISSAO))/12) BETWEEN 30 AND 100 THEN 17
        ELSE 0
    END AS PERCADICONALTEMPODECASA,
     CASE
        WHEN TRUNC((MONTHS_BETWEEN(SYSDATE,PFUNC.DATAADMISSAO))/12) BETWEEN  1 AND 10 THEN  TRUNC ((PFUNC.SALARIO * 0.05),2)
        WHEN TRUNC((MONTHS_BETWEEN(SYSDATE,PFUNC.DATAADMISSAO))/12) BETWEEN 10 AND 20 THEN  TRUNC ((PFUNC.SALARIO * 0.10),2)
        WHEN TRUNC((MONTHS_BETWEEN(SYSDATE,PFUNC.DATAADMISSAO))/12) BETWEEN 20 AND 30 THEN  TRUNC ((PFUNC.SALARIO * 0.13),2)
        WHEN TRUNC((MONTHS_BETWEEN(SYSDATE,PFUNC.DATAADMISSAO))/12) BETWEEN 30 AND 100 THEN TRUNC ((PFUNC.SALARIO * 0.17),2)
        ELSE 0
    END AS VALORADICIONAL,
    4 AS ANTECIPACAOSALARIAL2022
FROM PPESSOA
INNER JOIN PFUNC
ON PPESSOA.CODIGO = PFUNC.CODPESSOA
WHERE PFUNC.CODSITUACAO IN ('A', 'F', 'P') AND PFUNC.CODRECEBIMENTO = 'M'
ORDER BY VALORADICIONAL DESC;

-- Query retorna o total de funcionários não desligados por horário.
-- Tabelas: PFUNC e AHORARIO

SELECT PFUNC.CODHORARIO,
       COUNT(PFUNC.CODHORARIO) AS TOTALPORHORARIO 
FROM PFUNC
INNER JOIN AHORARIO
ON PFUNC.CODHORARIO = AHORARIO.CODIGO
WHERE (
        PFUNC.CODSITUACAO IN ('A', 'F', 'P') AND 
        PFUNC.CODRECEBIMENTO = 'M'
       )
GROUP BY PFUNC.CODHORARIO
ORDER BY TOTALPORHORARIO DESC;

-- Query retorna o histórico de alteração de horário de todos os colaboradores do tipo 'M'(mensalista) e que estão com a situação diferente de 'D' (desligado).

SELECT 
    PFHSTHOR.CHAPA,
    PFUNC.NOME,
    PFUNCAO.NOME AS DESCRICAO,
    PFUNC.CODSITUACAO,
    PFHSTHOR.DTMUDANCA,
    TRUNC((PFUNC.JORNADAMENSAL / 60),2) AS JORNADAMESAL,
    PFHSTHOR.CODHORARIO,
    AHORARIO.DESCRICAO,
    PFHSTHOR.RECMODIFIEDBY AS ALTERACAOUSUARIO
FROM PFHSTHOR
INNER JOIN AHORARIO
ON PFHSTHOR.CODHORARIO = AHORARIO.CODIGO
INNER JOIN PFUNC
ON  PFHSTHOR.CHAPA = PFUNC.CHAPA
INNER JOIN PFUNCAO
ON PFUNC.CODFUNCAO = PFUNCAO.CODIGO
WHERE PFUNC.CODSITUACAO != 'D' AND PFUNC.CODRECEBIMENTO = 'M'
ORDER BY PFUNC.NOME, PFHSTHOR.DTMUDANCA DESC;

-- Query retorna a quantidade de alterações de horário que foi realizada por cada colaborador, e conta quantas alterações de horário cada um deles teve.

SELECT 
    PFHSTHOR.CHAPA,
    COUNT(PFHSTHOR.DTMUDANCA) AS QUATIDADEDEALTERACAO
FROM PFHSTHOR
INNER JOIN AHORARIO
ON PFHSTHOR.CODHORARIO = AHORARIO.CODIGO
INNER JOIN PFUNC
ON  PFHSTHOR.CHAPA = PFUNC.CHAPA
INNER JOIN PFUNCAO
ON PFUNC.CODFUNCAO = PFUNCAO.CODIGO 
WHERE PFUNC.CODSITUACAO != 'D' AND PFUNC.CODRECEBIMENTO = 'M'
GROUP BY PFHSTHOR.CHAPA
ORDER BY QUATIDADEDEALTERACAO DESC;

--





